### ISSUE TITLE
Size allocated to member 'm_1DPtr' are wrong!

### ISSUE THREAD

**Issue by LuoxuanLove** [Liiii007/DOTS-Helper#3]
In Native2DArray.cs, the following code is used to allocate memory for 'm_1DPtr':
// m_1DPtr = (T**)UnsafeUtility.Malloc(**UnsafeUtility.SizeOf\<T>()** * xsize, alignment, allocator);

'm_1DPtr' is a T**, Pointing to a pointer of T. Only the size of T* (A pointer) needs to be allocated, not the size of T. Otherwise, extra memory may be allocated.

**Comment by Liiii007** [comment]
Sorry, I‘m not fully understand what you said, did you mean that the whole 2D array can be flat and can access by m_ptr[pastCount + i]? The 2D Array I wrote is something like vector<vector<int>> in c++(every 1D array may have different size, but not resizable).  
PS: I plan to re-write it using Native1DArray, maybe this is a better solution for me?

**Comment by Liiii007** [comment]
Oh, I got it. The problem is the wrong size of 1D pointer. I will fix it late. Thanks bro!!

**Comment by Liiii007** [comment]
Fixed it！
